apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
    selector:
    #will copy the labels from the pod definition file
    selectors:
      name: redis-pod
      app: demo-voting-app