apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels: 
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
     #the worker app has no services listening, so no port required
        